### ISSUE TITLE
Bug report - plugin can't kick player because of warns

### ISSUE THREAD

**Issue by Taogrin** [DevKrieger/DKBans#10]
**Version**
Which version of DKBans are you using (example: 2.0.0)
2.2.1
**Platform**
On which platform is DKBans running? (example: BungeeCord)
PaperMC
**Minecraft server Version**
Which minecraft version is your server using? (example: 1.8)
1.12.2
**Minecraft client Version**
Which minecraft version are you using? (example: 1.8)
1.12.2
**Describe the bug**
When player receives given number of warnings (in my case it was 2nd warn), he should be kicked but it seems like plugin is trying to kick player from asynchronous task which causes exception
Error log
Send you server log, which contains the error (Use Hastebin oder Pastebin).
https://pastebin.com/ifaQVXyA

**To Reproduce**
How do we reproduce this bug?
The way tho trigger this bug.

1. Use /warn <player>
2. Use /warn <player>
3. See error

**Comment by DevKrieger** [comment]
Fixed in newest version (V2.2.2)
