### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RikoDEV** [DevKrieger/DKBans#6]
**Version**
2.1.6

**Platform**
Waterfall

**Minecraft server Version**
1.13.2

**Minecraft client Version**
1.13.2

**Describe the bug**
Console error when player join the server.

Error log
https://hastebin.com/cuvelenube.bash

**To Reproduce**

1. Join the waterfall proxy server.
2. See error.

**Comment by DevKrieger** [comment]
Can you please send your whole Server log.

**Comment by RikoDEV** [comment]
Fixed... I made a mistake in the translation file.
