### ISSUE TITLE
Config Error. Please Help

### ISSUE THREAD

**Issue by AggroMC** [DevKrieger/DKBans#9]
**Version**
Newest

**Platform**
Bungeecord

**Minecraft server Version**
BungeeCord 1.8 - 1.14, Spigot 1.8.8

**Minecraft client Version**
1.8.9

**Describe the bug**
Die messages.yml config lässt sich nicht ändern. Immer wenn ich irgendwas ändere geht gar nichts mehr. Ich hab mir echt Mühe gegeben die config anzupassen und alles aber egal was ich mache es geht nicht. Meine Config ist hier: https://www.aggromc.de/temp/config.txt und falls das nicht geht noch mal hier: https://paste.dsyn.ga/KGzaSh4X94

Error log
Was im log steht: https://paste.dsyn.ga/Bqmy63xLTR
Ganzer log ausschnitt: https://paste.dsyn.ga/BizrI5b031

**To Reproduce**
Es passiert immer wenn man nur 1 String in der config ändert

"1. Use /ban <player>
2. Use /unban <player>
3. See error"

ich kann die obigen commands nichtmal ausführen weil das plugin nicht geladen wird.

bitte um hilfe

AggroMC (~Steve)

**Comment by DevKrieger** [comment]
Bitte wenden Sie bei Problemen mit der Konfiguration unseren Support.
